apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gnchaind.configMapName" . }}
data:
  {{- if .Values.genesis_file }}
  genesis.json: |-
    {{- .Values.genesis_file | nindent 6 }}
  {{- end }}