apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gnchaind.secretName" . }}
type: Opaque
data:
  {{- if .Values.validator_mnemonic }}
    validator_mnemonic: {{ .Values.validator_mnemonic | b64enc }}
  {{- end }}
  {{- if .Values.node_key }}
    node_key.json: {{ .Values.node_key | b64enc }}
  {{- end }}
  {{- if .Values.chain_file }}
    chain.yaml: |-
    {{- .Values.chain_file | b64enc  | nindent 6 }}
  {{- end }}